version: '3'

services:
  keycloak:
    container_name: keycloak
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - desafioklok

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - desafioklok

  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: desafio
      POSTGRES_PASSWORD: desafio
      POSTGRES_MULTIPLE_DATABASES: msclientdb,mssaledb,msproductdb,mspaymentdb
    networks:
      - desafioklok

networks:
  desafioklok:
    driver: bridge