
spring:
  application:
    name: mspayment
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://localhost:5433/mspaymentdb?createDatabaseIfNotExist=true
    username: desafio
    password: desafio
  jpa:
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

mq:
  queues:
    payment-sale: payment-sale
    sale-payment: sale-payment

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    name: ./logs/log-file.log