spring:
  application:
    name: mscloudgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEY_SERVER}


server:
  port: 8081


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZones: http://${EUREKA_SERVER}